language: node_js
notifications:
  email: false
after_success: npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: uK1TGgdI9TcynEZVbHQJEpkJqQvpW+QQhfu/pl7dWK47Ht91Fpwuwvl6x9nzLFdDeYWiXr3hGVQOqcT62eshKBFlpnI+u75PelAgPYOxpuZe1Q55rUezPDwr7udBVrsoMVr0GBJuMB6a7+wScSMlBYTJ1W2JuLvHxHM+OGBOAicmY6r37Zm50aV3OIikLEUdHi2+FNrm7DH3t6T1Rdh1jGnlSxleO+erEisFOWpCK+17gXm2q4pG9tOBMQPWjiNSvcUg60ACjWR4ZlK8AEBqkAzhPvrklv5/bVgD9RWU1wpXJSxx+NUHiJSH9Id9v/aKGh9rJU4uqnxBxcV4ieLTxHhZ/mrhkegEWgualM9LIj0PbnFqBDy0+DQBrvPlBVdwfQTczQegBUW2y3Gx1zdVTKu8g8bc9dR7Ael+0wmJ+27q9pERYSk8s6AFSvyPmdroLIDPzw02x78X+Nf6LwcST+WQXTV4Kb2C+Fk0QzyiwR44A00OR0zV0wV8TzGL/2QvSRnAXK9FiofAR6vbOQeDsIRZ65xLKiDhoWNwRsJTbhCt1u5ubx5uI4OYVzlSSOi+FVztBpJvZAQXaHUyZa3F5lqO2k5PemxMWhfqR+rwafDGhS0rdtiFhiPDeUeZgUQQjMvtsRlv8MUSVcNpJjFAPz/FCh7pdR6S1LJYt0AmyXM=
