language: node_js
notifications:
  email: false
before_script:
    - npm ls >/dev/null
    - npm run greenkeeper:update-lockfile
after_script:
    - npm run greenkeeper:upload-lockfile
after_success:
    - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: uK1TGgdI9TcynEZVbHQJEpkJqQvpW+QQhfu/pl7dWK47Ht91Fpwuwvl6x9nzLFdDeYWiXr3hGVQOqcT62eshKBFlpnI+u75PelAgPYOxpuZe1Q55rUezPDwr7udBVrsoMVr0GBJuMB6a7+wScSMlBYTJ1W2JuLvHxHM+OGBOAicmY6r37Zm50aV3OIikLEUdHi2+FNrm7DH3t6T1Rdh1jGnlSxleO+erEisFOWpCK+17gXm2q4pG9tOBMQPWjiNSvcUg60ACjWR4ZlK8AEBqkAzhPvrklv5/bVgD9RWU1wpXJSxx+NUHiJSH9Id9v/aKGh9rJU4uqnxBxcV4ieLTxHhZ/mrhkegEWgualM9LIj0PbnFqBDy0+DQBrvPlBVdwfQTczQegBUW2y3Gx1zdVTKu8g8bc9dR7Ael+0wmJ+27q9pERYSk8s6AFSvyPmdroLIDPzw02x78X+Nf6LwcST+WQXTV4Kb2C+Fk0QzyiwR44A00OR0zV0wV8TzGL/2QvSRnAXK9FiofAR6vbOQeDsIRZ65xLKiDhoWNwRsJTbhCt1u5ubx5uI4OYVzlSSOi+FVztBpJvZAQXaHUyZa3F5lqO2k5PemxMWhfqR+rwafDGhS0rdtiFhiPDeUeZgUQQjMvtsRlv8MUSVcNpJjFAPz/FCh7pdR6S1LJYt0AmyXM=
  - secure: KhbgDh54bRJi/aU2g3+xim39WOsXU4DNc5sc1j+H10fkIlyahxEQ7qjItwM1P15NmY7ga1SHNtEMPM4JOUO8yW69f//8FLm/PX5BK2dUckwpnhL1jhJE+6NOCyxa3AYPGcNnx6WTOWjnWzilVEtEWUWOnCp6i5ELrR8NEcDrF/eov6R78ByHSnVUUyl9PzlOcoQqzWTJtPc8Sj+8gnJV1WqjBVebGIUdAIr+ohMqK15C7VP8vi3gWbBF77MPwPXYJmEQWmNh2f/jKDReHs1GddbwVHjHyqihP4VlIZ+/1T5BeSBMK/fnESp9+OTayRHbRv8kVd89jQwnR7DfOwjodV/jOU0zYyOvlP4Jyh/FpcfDNn9LNQbxK/7g4zFTOhwkp4vrMwNjlT0hsz6V5EikegZhFpXPH1ZJUSGah44BRpqzdtIEeCzMTivamzeyobJ8tS6lR/Xts4sDqCuOR24WpbIcNYX7/CLZ8VBXN+wyGvkRPMzUBuvtoIXZOjms8tz4fRFisazzBFNnGm3c9MEk8R7s/nYg63vd3B/qmLCfaQHYMZF1cVdMZMOm5Cb1DVo0brjeNE5XesytQlSbVJ9GeimuT36uBoHLW+5wzcZc1y3F8kciQdU5WdCk64xeOrcZq2ylIfHKRaaeQ1U8+T9Svsk+bqNJJV/PL3Yg1fBqrxU=
